name: Deploy LMS_FE Dev
on:
  push:
    branches:
      - dev
    paths:
      - 'angular/**'
      - '.github/workflows/deploy_server_dev_fe.yml'
jobs:
  build:
    runs-on: dev
    name: Build LMS_FE Dev
    environment: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Node Module
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json,**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    
    - name: npm install
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        cd angular/
        export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
        # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm use 14.17
        node -v
        rm -rf node_modules/
        npm cache clean --force
        echo "=== INSTALL PACKAGE ==="
        npm install
        
    - name: Angular Build
      run: |
        cd angular/
        export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
        # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm use 14.17
        ng build --prod
      env: 
        CI: false

    - name: Remove appconfig
      run: |
        cd angular/dist/assets
        rm -rf appconfig.prod.json
        rm -rf /var/www/app_git/lms/fe_bk/*
        cp -rf /var/www/app_git/lms/fe/* /var/www/app_git/lms/fe_bk/
        rm -rf /var/www/app_git/lms/fe/*
        
    - name: Copy AngularBuild
      run: |
        cd angular/dist/
        cp -r . /var/www/app_git/lms/fe/
        
    - name: Update Env-Config
      run: |
        cd angular/
        echo '${{ secrets.APP_CONFIG_DEV }}' > appconfig.prod.json
      
    - name: Restart Nginx
      run: |
        cd angular/
        cp appconfig.prod.json /var/www/app_git/lms/fe/assets/
        sudo service nginx reload